added

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,11 +39,34 @@ jobs:
           aws-region: ${{ secrets.DEV_AWS_Region }}
 
       - name: Create ECR Repository if not exists
+        shell: bash
+        env:
+          aws_region: ${{ secrets.DEV_AWS_Region }}
+          ECR_REPOSITORY: ${{ github.event.repository.name }}
         run: |
-          echo "Checking ECR repository $ECR_REPOSITORY in region $aws_region..."
-          output=$(aws ecr describe-repositories --region "$aws_region" --repository-names "$ECR_REPOSITORY" 2>&1)
-          echo "$output"
-          aws ecr create-repository --repository-name "$ECR_REPOSITORY" --region "$aws_region"
+            echo "Checking ECR repository '$ECR_REPOSITORY' in region '$aws_region'..."
+            output=$(aws ecr describe-repositories \
+              --region "$aws_region" \
+              --repository-names "$ECR_REPOSITORY" 2>&1)
+        
+            exit_code=$?
+        
+            if [ $exit_code -ne 0 ]; then
+              if echo "$output" | grep -q "RepositoryNotFoundException"; then
+                echo "Repository not found. Creating '$ECR_REPOSITORY'..."
+                aws ecr create-repository \
+                  --repository-name "$ECR_REPOSITORY" \
+                  --region "$aws_region"
+                echo "✅ Repository created."
+              else
+                echo "❌ Unexpected error while describing repository:"
+                echo "$output"
+                exit 1
+              fi
+            else
+              echo "✅ ECR repository '$ECR_REPOSITORY' already exists."
+            fi
+        
 
       - name: Login to Docker Hub
         uses: docker/login-action@v1
